version: '3.8'
#
#services:
#  app:
#    image: trythisimage
#    build:
#      context: .
#    container_name: demo-spring-jpa-project
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#
#  postgresql:
#    image: postgres
#    ports:
#      - "60000:60000"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=student
#      -
#
#version: '3.1'
services:
  API:
    image: 'trythisimage.jar'
    ports:
      - "8080:8080"
    depends_on:
      postgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/student
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  postgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=student
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5