version: '2'

services:
  app:
    image: 'spring-jpa-project:latest'
    build:
      context: .
    container_name: demo
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/student
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=